version: "3"
services:
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: equipo9
        MYSQL_USER: user
        MYSQL_PASSWORD: password

